#ifndef GIRSMACROS_H
#define GIRSMACROS_H

#ifdef IRRECEIVER_1_PULLUP
#define IRRECEIVER_1_PULLUP_VALUE true
#else
#define IRRECEIVER_1_PULLUP_VALUE false
#endif

#ifdef IRRECEIVER_2_PULLUP
#define IRRECEIVER_2_PULLUP_VALUE true
#else
#define IRRECEIVER_2_PULLUP_VALUE false
#endif

#ifdef IRRECEIVER_3_PULLUP
#define IRRECEIVER_3_PULLUP_VALUE true
#else
#define IRRECEIVER_3_PULLUP_VALUE false
#endif

#ifdef IRRECEIVER_4_PULLUP
#define IRRECEIVER_4_PULLUP_VALUE true
#else
#define IRRECEIVER_4_PULLUP_VALUE false
#endif

#ifdef IRRECEIVER_5_PULLUP
#define IRRECEIVER_5_PULLUP_VALUE true
#else
#define IRRECEIVER_5_PULLUP_VALUE false
#endif

#ifdef IRRECEIVER_6_PULLUP
#define IRRECEIVER_6_PULLUP_VALUE true
#else
#define IRRECEIVER_6_PULLUP_VALUE false
#endif

#ifdef IRRECEIVER_7_PULLUP
#define IRRECEIVER_7_PULLUP_VALUE true
#else
#define IRRECEIVER_7_PULLUP_VALUE false
#endif

#ifdef IRRECEIVER_8_PULLUP
#define IRRECEIVER_8_PULLUP_VALUE true
#else
#define IRRECEIVER_8_PULLUP_VALUE false
#endif




#endif // ! GIRSMACROS_H
